### ISSUE TITLE
Collector fails to send payload over HTTP2 with the `{:exceeds_window_size, :request, 65536}` error

### ISSUE THREAD

**Issue by arkgil** [buildkite/test_collector_elixir#3]
Hi there 👋 

At the end of the test suite, the collector fails with the following stacktrace:

```
** (CaseClauseError) no case clause matching: {:error, %Mint.HTTP2{buffer: <<0, 0, 4, 8, 0, 0, 0, 0, 0, 127, 255, 0, 0>>, client_settings: %{enable_push: true, max_concurrent_streams: 100, max_frame_size: 16384}, client_settings_queue: {[[]], []}, decode_table: %HPAX.Table{entries: [], length: 0, max_table_size: 4096, size: 0}, encode_table: %HPAX.Table{entries: [], length: 0, max_table_size: 4096, size: 0}, headers_being_processed: nil, hostname: "analytics-api.buildkite.com", mode: :active, next_stream_id: 3, open_client_stream_count: 0, open_server_stream_count: 0, ping_queue: {[], []}, port: 443, private: %{}, proxy_headers: [], ref_to_stream_id: %{}, scheme: "https", server_settings: %{enable_connect_protocol: false, enable_push: true, initial_window_size: 65536, max_concurrent_streams: 128, max_frame_size: 16777215, max_header_list_size: :infinity}, socket: {:sslsocket, {:gen_tcp, #Port<0.335>, :tls_connection, :undefined}, [#PID<0.3828.0>, #PID<0.3827.0>]}, state: :open, streams: %{}, transport: Mint.Core.Transport.SSL, window_size: 65535}, %Mint.HTTPError{module: Mint.HTTP2, reason: {:exceeds_window_size, :request, 65536}}}
--
  | (buildkite_test_collector 0.1.0) lib/buildkite_test_collector/http_transport.ex:18: BuildkiteTestCollector.HttpTransport.send/1
  | (buildkite_test_collector 0.1.0) lib/buildkite_test_collector/formatter.ex:104: BuildkiteTestCollector.Formatter.terminate/2
  | (stdlib 3.17) gen_server.erl:733: :gen_server.try_terminate/3
  | (stdlib 3.17) gen_server.erl:918: :gen_server.terminate/10
  | (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

This looks like the error described in https://github.com/elixir-tesla/tesla/issues/394.

**Comment by jimsynz** [comment]
Hi @arkgil thanks for the report.

I'll take a look at fixing this first thing in the morning.  The payloads are already batched (in groups of 500) so worst case we can reduce the batch size to fix.

**Comment by arkgil** [comment]
Can I somehow configure the batch size to try if it helps?

**Comment by jimsynz** [comment]
Yup. You can add `:batch_size` to your `:buildkite_test_collector` configuration in `test.exs` eg:

```
import Config

config :buildkite_test_collector,
  api_key: "my redacted key",
  batch_size: 100
```

Hope that helps!

**Comment by arkgil** [comment]
Thanks! Will try it out.

**Comment by arkgil** [comment]
Alright, batch size of 100 fixes the issues 👍

**Comment by joshprice** [comment]
Closing this for now, we'll reduce default batch size to prevent this from occurring, and investigate ways to resolve the underlying problem too. Thanks for raising @arkgil ❤️

**Comment by joshprice** [comment]
Thanks for reporting. I've updated the default to 100 (https://github.com/buildkite/test_collector_elixir/commit/34901e4e1053421de7ce280cf6f3d4380df6faab), but please let us know what value(s) worked for you.

This will be in the next release.

**Comment by arkgil** [comment]
@joshprice yup, we've set the batch size to 100, not issues so far. Thanks!
