### ISSUE TITLE
`@tag :skip` causes a KeyError

### ISSUE THREAD

**Issue by ryansch** [buildkite/test_collector_elixir#4]
```
** (KeyError) key :module not found in: %{async: true, describe: nil, describe_line: nil, file: "redacted", line: 24, registered: %{}, skip: true, test_type: :test}
(buildkite_test_collector 0.1.1) lib/buildkite_test_collector/test_result.ex:67: BuildkiteTestCollector.TestResult.new/3
(buildkite_test_collector 0.1.1) lib/buildkite_test_collector/formatter.ex:74: BuildkiteTestCollector.Formatter.handle_cast/2
(stdlib 3.17.1) gen_server.erl:695: :gen_server.try_dispatch/4
(stdlib 3.17.1) gen_server.erl:771: :gen_server.handle_msg/6
(stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
--
Last message: {:"$gen_cast", {:test_finished, %ExUnit.Test{case: Mix.Tasks.TranslookupTest, logs: "", module: Mix.Tasks.TranslookupTest, name: :"test writes out a translated PO file", state: {:skipped, "due to skip tag"}, tags: %{async: true, describe: nil, describe_line: nil, file: "redacted", line: 24, registered: %{}, skip: true, test_type: :test}, time: 0}}}
```

I've been able to replicate this behaviour with other specs that also include the skip tag.

**Comment by jimsynz** [comment]
Hi @ryansch.

Thanks for the report. I will get this sorted out today.

**Comment by jimsynz** [comment]
Fixed in version `0.1.2`.

**Comment by ryansch** [comment]
@jimsynz Thanks!

The commit for `0.1.2` is not on `main` and there's no github release for it. Was that intentional?

**Comment by jimsynz** [comment]
my bad. sorry! covid brain.
